version: 2
jobs:
  service_up:
    docker:
    - image: circleci/python:3.6.6-node
    working_directory: ~/singnet
    environment:
      ORG: singnet
      DOCKER_ORG: singularitynet
      DOCKER_CONTEXT: https://github.com/singnet/opencog-services.git
      DOCKER_BASIC_IMAGE_NAME: senna_opencog_services_basic
      DOCKER_IMAGE_NAME: _opencog_services_staging
      DOCKER_CONTAINER_NAME: _OPENCOG_SERVICES_STAGING
      REPO_NAME: opencog-services
      SERVICE_NAME: opencog
      SERVICE_RUN_SCRIPT: bin/server
      TEST_SCRIPT: bin/runTests
      COMPLIANCE_CHECK_SCRIPT: scripts/compliance_check.sh
    steps:
    - run:
        name: Build basic docker image
        command: |
          ssh -o "StrictHostKeyChecking no" $SSH_USER@$SSH_HOST << EOF
            docker image build -t $DOCKER_BASIC_IMAGE_NAME https://raw.githubusercontent.com/singnet/opencog-services/master/.circleci/basic_dockerfile
          EOF
    - run:
        name: Build Docker container
        command: |
          ssh -o "StrictHostKeyChecking no" $SSH_USER@$SSH_HOST << EOF
            docker stop $CIRCLE_USERNAME$DOCKER_CONTAINER_NAME || true
            docker rm $CIRCLE_USERNAME$DOCKER_CONTAINER_NAME || true 
            docker build --no-cache -t $CIRCLE_USERNAME$DOCKER_IMAGE_NAME $DOCKER_CONTEXT
          EOF
    - run:
        name: Start Service
        command: |
          ssh -o "StrictHostKeyChecking no" $SSH_USER@$SSH_HOST << EOF
            docker run --name $CIRCLE_USERNAME$DOCKER_CONTAINER_NAME \
              -di $CIRCLE_USERNAME$DOCKER_IMAGE_NAME $SERVICE_RUN_SCRIPT
          EOF
    - run:
        name: Execute compliance check
        command: |
          ssh -o "StrictHostKeyChecking no" $SSH_USER@$SSH_HOST << EOF
            docker exec -i $CIRCLE_USERNAME$DOCKER_CONTAINER_NAME $COMPLIANCE_CHECK_SCRIPT
          EOF
    - run:
        name: Execute regression tests
        command: |
          ssh -o "StrictHostKeyChecking no" $SSH_USER@$SSH_HOST << EOF
            docker exec -i $CIRCLE_USERNAME$DOCKER_CONTAINER_NAME $TEST_SCRIPT
          EOF
    - run:
        name: Deploy service
        command: |
          ssh -o "StrictHostKeyChecking no" $SSH_USER@$SSH_HOST << EOF
              if [ $CIRCLE_BRANCH = "master" ]; then
                  echo "Deploying service"
                  docker stop senna$DOCKER_CONTAINER_NAME
                  docker stop $CIRCLE_USERNAME$DOCKER_CONTAINER_NAME
                  docker rm senna$DOCKER_CONTAINER_NAME
                  docker rm $CIRCLE_USERNAME$DOCKER_CONTAINER_NAME
                  docker rmi senna$DOCKER_IMAGE_NAME
                  docker image tag $CIRCLE_USERNAME$DOCKER_IMAGE_NAME senna$DOCKER_IMAGE_NAME
                  docker rmi $CIRCLE_USERNAME$DOCKER_IMAGE_NAME
                  docker run --name $CIRCLE_USERNAME$DOCKER_CONTAINER_NAME \
                      --restart unless-stopped \
                      -di $CIRCLE_USERNAME$DOCKER_IMAGE_NAME $SERVICE_RUN_SCRIPT
              else
                  echo "Branch: $CIRCLE_BRANCH"
                  echo "Branch: service WILL NOT be deployed"
              fi
          EOF

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - service_up
